version: '3.8'

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie-honeypot
    ports:
      - "2222:2222" # SSH
      - "2223:2223" # Telnet
    volumes:
      - cowrie-var:/cowrie/cowrie-git/var
      - cowrie-etc:/cowrie/cowrie-git/etc
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always

volumes:
  cowrie-var:
  cowrie-etc:
  mongodb-data:
